# Generated by Django 5.1.6 on 2025-04-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='otp_timeout_before_retry',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='otp_verify',
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
