# Generated by Django 5.1.6 on 2025-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usermodel_max_otp_try_remove_usermodel_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
